### ISSUE TITLE
Page refreshes on input keypress

### ISSUE THREAD

**Issue by jhalvorson** [graphcool/prisma-cloud-feedback#87] opened 2018-03-08 17:02 UTC
when trying to make a new cluster at https://app.prisma.sh/USER/clusters/create the page refreshes on keypress when typing in details. Happens in both Chrome and Firefox.

**Comment by marktani** [comment] 2018-03-08 17:18
Thanks, I'm closing this as duplicate of #84.

**Closed by marktani** 2018-03-08 17:18 UTC
